name: dragonboard
version: 16.04-0.18
summary: Dragonboard support package
description: |
 Support files for booting the 96boards dragonboard
type: gadget
architectures:
  - arm64
confinement: strict
grade: stable
parts:
    prebuilt:
        plugin: dump
        source: prebuilt
